conversation_history = {
"role": "system",
"content": "You are a helpful and kind AI Assistant, who knows everything about the ROM Global project. You will answer politely and concisely, but can follow up by asking if the user would like to know more, at which point you may develop further on the topic." },
{ "role": "assistant",
"content": "Hi, how can I help you today?" }
{ "role": "user",
 "content": "What is the Assignment Declaration?" },
{ "role": "assistant",
"content": "The Assignment Declaration is a document that is signed by the ROM Expert at the phase of recruitment/mobilisation." },
{ "role": "user",
"content": "What does the MC do after the Assignment Declaration is signed?" },
{ "role": "assistant",
"content": "The MC makes the first contact with the ROM Expert and, if necessary, collects the ROM Expert's contact details and passport, and other personal information, when relevant." },
{ "role": "user",
"content": "What contact details does the MC collect from the ROM Expert?" },
{ "role": "assistant",
"content": "The MC collects the ROM Expert's contact details and passport, and other personal information, when relevant." },
{ "role": "user",
"content": "Is it necessary for the MC to collect the ROM Expert's contact details?" },
{ "role": "assistant",
"content": "Yes, it is necessary for the MC to collect the ROM Expert's contact details and passport, and other personal information, when relevant." },
{ "role": "user",
"content": "What other personal information does the MC collect from the ROM Expert?" },
{ "role": "assistant",
"content": "The MC collects other personal information from the ROM Expert, when relevant." },
{ "role": "user",
"content": "What is included in the preliminary assessment?" },
{ "role": "assistant",
"content": "The preliminary assessment identifies missing information and key points to prepare before the field mission." },
{ "role": "user",
"content": "Who visits the Financing Institution for the ROM review mission?" },
{ "role": "assistant",
"content": "Two assigned ROM Experts visit the Financing Institution." },
{ "role": "user",
"content": "What happens after the preliminary assessment is submitted?" },
{ "role": "assistant",
"content": "The preliminary assessment is submitted to the ROM Coordination Unit for the final approval of the mission scope and dates." },
{ "role": "user",
"content": "Who approves the mission scope and dates?" },
{ "role": "assistant",
"content": "The ROM Coordination Unit approves the mission scope and dates." },
{ "role": "user",
"content": "The ROM Expert and the MC organise an introductory call with the Implementing Partner (IP) to discuss the Mission preparation details (for example pending documentation transfer by the IP, agreement on key informants, schedules of meetings and in-country travel, logistics)." },
{ "role": "assistant",
"content": "The purpose of the introductory call is to discuss the Mission preparation details, such as pending documentation transfer by the IP, agreement on key informants, schedules of meetings and in-country travel, and logistics." },
{ "role": "user",
"content": "Who is involved in the introductory call?" },
{ "role": "assistant",
"content": "The ROM Expert and the MC are involved in the introductory call with the Implementing Partner (IP)." },
{ "role": "user",
"content": "What kind of documentation is the IP expected to transfer?" },
{ "role": "assistant",
"content": "The IP is expected to transfer pending documentation." },
{ "role": "user",
"content": "What is agreed upon during the introductory call?" },
{ "role": "assistant",
"content": "During the introductory call, agreement is reached on key informants, schedules of meetings and in-country travel, and logistics." },
{ "role": "user",
"content": "Who from the ROM Global operational team interacts with the ROM Expert?" },
{ "role": "assistant",
"content": "Every member of the ROM Global operational team interacts with the ROM Expert at every step of the process." },
{ "role": "user",
"content": "What is the purpose of the ROM Expert?" },
{ "role": "assistant",
"content": "The ROM Expert is responsible for providing guidance and support to the ROM Global operational team throughout the process." },
{ "role": "user",
"content": "What is the role of the ROM Global operational team?" },
{ "role": "assistant",
"content": "The ROM Global operational team is responsible for managing the process and ensuring that all requirements are met." },
{ "role": "user",
"content": "What process does the ROM Global operational team follow?" },
{ "role": "assistant",
"content": "The ROM Global operational team follows a process that involves interacting with the ROM Expert at every step." },
{ "role": "user",
"content": "How does the ROM Expert provide guidance and support?" },
{ "role": "assistant",
"content": "The ROM Expert provides guidance and support to the ROM Global operational team by offering advice and expertise throughout the process." },
{ "role": "user",
"content": "What does the ROM expert do?" },
{ "role": "assistant",
"content": "The ROM expert prepares comments to be added to BN after the briefing with the OM of the EUD during the field phase." },
{ "role": "user",
"content": "Who is the Strand Leader?" },
{ "role": "assistant",
"content": "The Strand Leader is the person responsible for the Mission." },
{ "role": "user",
"content": "Who is the assigned SQM?" },
{ "role": "assistant",
"content": "The assigned SQM is the person responsible for managing the interventions managed by the EUDs." },
{ "role": "user",
"content": "Who is the OM of the EUD?" },
{ "role": "assistant",
"content": "The OM of the EUD is the person responsible for overseeing the field phase." },
{ "role": "user",
"content": "What is the longer than normal desk phase for remote ROM reviews?" },
{ "role": "assistant",
"content": "The longer than normal desk phase for remote ROM reviews is called the preparatory desk phase." },
{ "role": "user",
"content": "What does the preparatory desk phase encompass?" },
{ "role": "assistant",
"content": "The preparatory desk phase encompasses the normal desk phase as well as the setup and implementation of key interviews that can be conducted remotely." },
{ "role": "user",
"content": "What is the purpose of the preparatory desk phase?" },
{ "role": "assistant",
"content": "The purpose of the preparatory desk phase is to enable the collection of primary and secondary sources to triangulate data and evidence." },
{ "role": "user",
"content": "What type of interviews are conducted during the preparatory desk phase?" },
{ "role": "assistant",
"content": "Key interviews that can be conducted remotely are conducted during the preparatory desk phase." },
{ "role": "user",
"content": "What is the outcome of the preparatory desk phase?" },
{ "role": "assistant",
"content": "The outcome of the preparatory desk phase is the collection of primary and secondary sources to triangulate data and evidence." },
{ "role": "user",
"content": "What is Lot 1?" },
{ "role": "assistant",
"content": "Lot 1 is ROM for Asia and Pacific, Latin America, Caribbean, and Centrally Managed Thematic Interventions." },
{ "role": "user",
"content": "What does Lot 1 cover?" },
{ "role": "assistant",
"content": "Lot 1 covers ROM for Asia and Pacific, Latin America, Caribbean, and Centrally Managed Thematic Interventions." },
{ "role": "user",
"content": "What is ROM?" },
{ "role": "assistant",
"content": "ROM stands for Results-Oriented Management." },
{ "role": "user",
"content": "What regions does Lot 1 cover?" },
{ "role": "assistant",
"content": "Lot 1 covers Asia and Pacific, Latin America, Caribbean, and Centrally Managed Thematic Interventions." },
{ "role": "user",
"content": "What are Centrally Managed Thematic Interventions?" },
{ "role": "assistant",
"content": "Centrally Managed Thematic Interventions are interventions that are managed centrally by a governing body." },
{ "role": "user",
"content": "What do we need to do to prepare for the meeting?" },
{ "role": "assistant",
"content": "We need to exchange emails with the IPs and project stakeholders to agree on the agenda." },
{ "role": "user",
"content": "Who should we be exchanging emails with?" },
{ "role": "assistant",
"content": "We should be exchanging emails with the IPs and project stakeholders." },
{ "role": "user",
"content": "What is the purpose of exchanging emails?" },
{ "role": "assistant",
"content": "The purpose of exchanging emails is to agree on the agenda." },
{ "role": "user",
"content": "What should be included in the emails?" },
{ "role": "assistant",
"content": "The emails should include the agenda for the meeting." },
{ "role": "user",
"content": "How will the emails help us prepare for the meeting?" },
{ "role": "assistant",
"content": "The emails will help us agree on the agenda for the meeting." },
{ "role": "user",
"content": "What is the purpose of the draft schedule?" },
{ "role": "assistant",
"content": "The purpose of the draft schedule is to provide a template for meetings shared by the MC." },
{ "role": "user",
"content": "Who will receive the draft schedule?" },
{ "role": "assistant",
"content": "The draft schedule will be shared with the Ips." },
{ "role": "user",
"content": "What is the MC?" },
{ "role": "assistant",
"content": "The MC stands for the Meeting Coordinator." },
{ "role": "user",
"content": "What is included in the template?" },
{ "role": "assistant",
"content": "The template includes the date, time, and location of the meetings." },
{ "role": "user",
"content": "What is the next step after preparing the draft schedule?" },
{ "role": "assistant",
"content": "The next step after preparing the draft schedule is to share it with the Ips." },
{ "role": "user",
"content": "What is the Desk Study document?" },
{ "role": "assistant",
"content": "It is a document that confirms the key stakeholders to be met/interviewed." },
{ "role": "user",
"content": "What is the purpose of the Desk Study document?" },
{ "role": "assistant",
"content": "The purpose of the Desk Study document is to confirm the key stakeholders to be met/interviewed." },
{ "role": "user",
"content": "How does the Desk Study document help to identify key stakeholders?" },
{ "role": "assistant",
"content": "The Desk Study document helps to identify key stakeholders by confirming who should be met/interviewed." },
{ "role": "user",
"content": "What kind of information is included in the Desk Study document?" },
{ "role": "assistant",
"content": "The Desk Study document includes information about the key stakeholders to be met/interviewed." },
{ "role": "user",
"content": "What is the importance of studying the Desk Study document?" }